name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build:prod
      - run: cp quotes.json dist/
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Setup known_hosts
        run: echo '${{ secrets.DEPLOY_HOST }} ${{ secrets.DEPLOY_KNOWN_HOST }}' >> ~/.ssh/known_hosts
      - name: Sync project files
        run: rsync -avzr --delete ${GITHUB_WORKSPACE}/dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.REMOTE_PATH }}
      - name: Check Node Version  
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "echo `$(which node) -v`"
      - name: Run Database Migration
        run: ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 'source ~/.nvm/nvm.sh; ${{ secrets.DB_ENV }} node ${{ secrets.REMOTE_PATH }}/import.js ${{ secrets.REMOTE_PATH }}/quotes.json'